experiment_name: census_experiments
defaults:
  - labels: census
  - model: random_forest
data:
  test_size: 0.3
  random_state: 42

hydra:
  sweeper:
    params:
      model.model_parameters.max_depth: 10,15,30,50,100,300
      model.model_parameters.n_estimators: 50,100,200,500