experiment_name: census_experiments
data:
  test_size: 0.3
  random_state: 42
random_forest:
  n_estimators: 100
  criterion: 'gini'
  max_depth: 13
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: 'sqrt'
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: true
  oob_score: false
  n_jobs: null
  random_state: 42
  verbose: 0
  warm_start: false
  class_weight: "balanced"
  ccp_alpha: 0.0
  max_samples: null
categorical:
  - "workclass"
  - "education"
  - "marital-status"
  - "occupation"
  - "relationship"
  - "race"
  - "sex"
  - "native-country"
label:
  - "salary"

hydra:
  sweeper:
    params:
      random_forest.max_depth: 10,15,30,50,100,300
      random_forest.n_estimators: 50,100,200,500

